---
name: "Watchbook"
guid: "496d23d6-7207-4729-86fb-875d3837e4d3"
version: 1
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "Plugin for Watchbook integration with Jellyfin."
description: >
  Plugin for Watchbook integration with Jellyfin.
category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Watchbook.dll"
changelog: >
  changelog
